config/routes.rb
Rails.application.routes.draw do
  get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'

  devise_for :users
  # Define the root route for unauthenticated users
  unauthenticated :user do
    root to: 'homes#index', as: :unauthenticated_root
  end
  # Define the root route for authenticated users (categories#index)
  authenticated :user do
    root to: 'categories#index', as: :authenticated_root
  end
  resources :categories, only: %i[index new  create destroy edit update] do
    resources :expenses, only: [:index, :new, :create, :destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.role == 'admin'
      can :manage, :all
    else
      can :read, :all
      can :manage, Category, author_id: user.id
      can :manage, Expense, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :expense_categories, dependent: :destroy
  has_many :expenses, through: :expense_categories
  validates :name, :icon, presence: true
  ICON_OPTIONS = ['🍔', '🛒', '🚗', '🐶', '📚', '💻', '🎁', '🏠', '🏥', '🎬', '👔', '🎓', '✈️', '⚽️', '🎮', '🎧', '🎸', '🎨', '🎥',
                  '💰', '🏆', '☎️', '📧', '🌍', '👫', '👪'].freeze
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :expense_categories
  has_many :categories, through: :expense_categories

  validates :amount, numericality: { greater_than: 0 }
  validates :name, presence: true

  validates :category_ids, presence: { message: 'must be selected' }
end

app/models/expense_category.rb
class ExpenseCategory < ApplicationRecord
  belongs_to :category
  belongs_to :expense
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :expenses

  validates :name, presence: true, allow_blank: false, length: { minimum: 2, maximum: 30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @categories = current_user.categories.includes(:expenses)
  end

  def new
    @category = Category.new
    @icon_options = Category::ICON_OPTIONS
  end

  def edit
    @category = Category.find(params[:id])
    @icon_options = Category::ICON_OPTIONS
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      flash[:notice] = 'Expense category successfully Updated.'
      redirect_to categories_path
    else
      flash.now[:alert] = 'Category cannot be updated.'
      render :edit
    end
  end

  def destroy
    @category = current_user.categories.find(params[:id])
    @category.destroy
    redirect_to categories_path, alert: 'Expense category deleted successfully.'
  end

  def create
    @user = current_user
    @category = @user.categories.build(user_id: @user.id, **category_params)
    if @category.save
      redirect_to categories_path, notice: 'New expense category successfully created.'
    else
      redirect_to categories_path, alert: 'Cannot create a new expense category'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @expenses = @category.expenses.order(created_at: :desc)
    @total = @expenses.sum(:amount)
  end

  def new
    @category = Category.find(params[:category_id])
    @expense = Expense.new
  end

  def create
    @category = Category.find_by(id: params[:category_id])
    @categories = Category.all

    if @categories.empty?
      redirect_to root_path, alert: 'No categories available'
      return
    end

    @expense = @category.expenses.build(expense_params)

    if @expense.save
      redirect_to category_expenses_path(category_id: @category.id), notice: 'Expense was successfully created.'
    else
      flash.now[:alert] = 'Expense cannot be created.'
      render :new
    end
  end

  def destroy
    @expense = Expense.find(params[:id])
    @categories = @expense.categories # Get the categories associated with the expense

    @categories.each do |category|
      expense_category = category.expense_categories.find_by(expense_id: @expense.id)
      expense_category&.destroy # Destroy the expense_category if it exists
    end

    @expense.destroy
    redirect_to category_expenses_path(category_id: params[:category_id]), alert: 'Expense deleted successfully.'
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, category_ids: []).merge(author_id: current_user.id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/categories/edit.html.erb
<main class="category-section">
  <div class="category-container">
    <%= render "shared/head", title: 'Edit Category', back: true %>
    <div class="success-fail">
     <% if flash[:notice] %>
        <%= render 'shared/message', message: flash[:notice], status: 'success' %>
      <% end %>

      <% if flash[:alert] %>
        <%= render 'shared/message', message: flash[:alert], status: 'danger' %>
      <% end %>
    </div>
    <%= form_for @category, url: category_path(@category), method: :patch, class: 'form-horizontal' do |f| %>
    <div class="category-edit-form mt-5 bg-light">
        <div class="card p-3 p-md-5">
            <%= f.label :name, class: 'control-label col-sm-2' %>
            <%= f.text_field :name, class: 'form-control' %>
            <%= f.label :icon, class: 'control-label col-sm-2' %>
            <%= f.select :icon, @icon_options, { selected: @category.icon, prompt: "Select an Icon" }, { class: 'form-control form-control-lg mb-1', 'aria-label': 'Select an Icon' } %>
          <div class="col-sm-10">
          </div>
        </div>
    </div>
    <div class="mt-auto">
      <div class="add-category-container d-flex justify-content-center px-3 px-md-5 py-3">
            <%= f.submit 'Update Category', class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

  </div>
</main>

app/views/categories/index.html.erb
<main class="category-section">
  <div class="category-container">
    <%= render "shared/head", title: 'categories', back: false %>
    <div class="success-fail">
      <% if flash[:notice] %>
        <%= render 'shared/message', message: flash[:notice], status: 'success' %>
      <% end %>

      <% if flash[:alert] %>
        <%= render 'shared/message', message: flash[:alert], status: 'danger' %>
      <% end %>
    </div>

    <% if @categories.empty? %>
      <div class="container-fluid p-4">
        <h1>Welcome to this mobile web application where you can manage your budget</h1>
      </div>
    <% else %>
      <ul class="list-group mt-5 category-container bg-light">
         <%= render "shared/category_card"%>
      </ul>
    <% end %>
      <div class="mt-auto">
      <div class="add-category-container d-flex justify-content-center px-3 px-md-5 py-3">
        <%= link_to "ADD CATEGORY", new_category_path, class: 'btn btn-outline-light btn-lg' %>
      </div>
    </div>
  </div>
</main>

app/views/categories/new.html.erb
<section class="category-section">
      <div>
        <%= render "shared/head", title: "add category", back: true %>
    </div>
    <div class="form-container">
    <%= form_with model: @category do |form| %>
      <div class="card p-3 p-md-5">
        <%= form.text_field :name, required: true, placeholder: "Enter New Category", class: 'form-control'%>
        <%= form.select :icon, @icon_options, { prompt: "Select an Icon" }, { class: 'form-control form-control-lg mb-1', 'aria-label': 'Select an Icon' } %>
      </div>

      <div class="add-category-container d-flex justify-content-center px-3 px-md-5 py-3 py-md-5">
        <%= form.submit "Create category", class: 'btn btn-primary btn-lg w-80' %>
      </div>
    <% end %>
  </div>
  </section>

app/views/expenses/index.html.erb
<div class="expen-container">
<%= render "shared/head", title: 'Expenses', back: true %>

<div class="alert-section">
  <% if flash[:notice] %>
    <%= render 'shared/message', message: flash[:notice], status: 'notice' %>
  <% end %>

  <% if flash[:alert] %>
    <%= render 'shared/message', message: flash[:alert], status: 'alert' %>
  <% end %>
</div>

  <div class="card expense-container bg-light m-1 p-1">
    <% if @expenses.empty? %>
      <ul class = "bg-light m-0 p-0 bg-light">
        <li class="category-list  mx-2 d-flex justify-content-between shadow-lg px-3 py-5 my-5 bg-white">
        <div class="icon-container text-3xl me-4"><%= @category.icon %></div>
        <div class="text-md opacity-75 font-semibold text-uppercase"><%= @category.name %></div>
        <div class="d-inline-flex">
            <%= link_to edit_category_path(@category), class: 'btn btn-success btn-sm mr-1' do %>
              <i class="fas fa-edit text-xl"></i>
            <% end %>
        <%= button_to category_path(@category), method: :delete, class: 'btn btn-danger btn-sm mr-1' do %>
          <i class="fas fa-trash"></i>
        <% end %>
        </div>
      </li>
        <h5>There is no expense for this category</h5>
      <ul>
    <% else %>
      <ul class="bg-light m-0 p-0 bg-light">
        <li class="category-list px-2 d-flex justify-content-between shadow-lg py-5 my-5 bg-white">
          <h2 class="font-semibold text-md text-black">Total Amount:</h2>
          <span class="font-semibold text-md">$<%= @total %></span>

        </li>
        <li class="category-list  mx-2 d-flex justify-content-between shadow-lg px-3 py-5 my-5 bg-white">
          <div class="icon-container text-3xl me-4"><%= @category.icon %></div>
          <div class="text-md opacity-75 font-semibold text-uppercase"><%= @category.name %></div>
          <div class="d-inline-flex">
              <%= link_to edit_category_path(@category), class: 'btn btn-success btn-sm mr-1' do %>
                <i class="fas fa-edit text-xl"></i>
              <% end %>
          <%= button_to category_path(@category), method: :delete, class: 'btn btn-danger btn-sm mr-1' do %>
            <i class="fas fa-trash"></i>
          <% end %>
          </div>
        </li>

        <% @expenses.each do |expense| %>
          <li class="card mb-3">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center">
                  <div class="icon-container text-3xl me-4"><%= @category.icon %></div>
                  <span class="text-muted font-semibold"><%= expense.name %></span>
                <span class="font-semibold text-md">$<%= format('%.2f', expense.amount) %></span>
              </div>
            </div>
            <div class="card-footer d-flex justify-content-between align-items-center p-1">
              <span class="text-muted font-semibold"><%= expense.created_at.strftime('%d-%m-%Y') %></span>
              <%= button_to category_expense_path(@category, expense), method: :delete, class: 'btn btn-danger btn-sm' do %>
                <i class="fas fa-trash"></i>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
<div class="mt-auto">
  <div class="add-category-container mt- d-flex justify-content-center px-3 py-4">
    <%= link_to "ADD EXPENSE", new_category_expense_path(category_id: @category.id), class: 'btn btn-outline-light btn-lg text-white py-3' %>
  </div>
</div>
</div>

app/views/expenses/new.html.erb
<main class="expense_section">
  <div class="expense-container"> 
    <div>
        <%= render "shared/head", title: "add Expense", back: true %>
    </div>
    <% if flash[:notice].present? %>
        <div class="notice">
            <%= flash[:notice] %>
        </div>
    <% end %>
    <div class="form-container">
    <%= form_with model: [@category, @expense], url: category_expenses_path(@category), method: :post do |form| %>
    <div class="border p-5 vh-80">
        <div class="form-floating mb-3 ">
        <%= form.text_field :name, class: "form-control", placeholder: "Name", required: true %>
        <%= form.label :name, class: "col-sm-2 col-form-label" %>
        </div>

        <div class="form-floating mb-3">
        <%= form.number_field :amount, class: "form-control", placeholder: "Amount", required: true %>
        <%= form.label :amount, class: "col-sm-2 col-form-label" %>
        </div>
        
        <div class="mb-3">
            <%= form.select :category_ids,
                Category.all.map { |category| [category.name, category.id] },
                { include_blank: 'Category' },
                { class: 'form-select form-select-lg mb-1', multiple: true, 'aria-label': 'multiple select example' }
            %>
        </div>
    </div>
    
    <div class="add-category-container d-flex justify-content-center px-5 py-7">
    <%= form.submit "Create Expense", class: 'btn btn-outline-light my-2 btn-lg w-80 text-uppercase' %>
  </div>
  <% end %>
</div>
</div>
</main>

app/views/homes/index.html.erb
<div class="container d-flex flex-column justify-content-between" style="height: 90vh">
  <div class="d-flex flex-column text-center justify-content-center" style="flex: 1">
    <h1 class="Splash-title">Budget Expense</h1>
    <div class="d-grid gap-2 fixed-bottom p-3">
      <%= link_to "LOG IN", new_user_session_path, class: 'btn btn-primary btn-lg' %>
      <%= link_to "SIGN UP", new_user_registration_path, class: 'btn btn-dark btn-lg' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetExpenseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <script src="https://kit.fontawesome.com/9e6b5903a6.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />

    <!-- Add Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_category_card.html.erb
 <% @categories.each do |category| %>
    <%= link_to category_expenses_path(category_id: category.id), class: 'list-group-item list-group-item-action d-flex justify-content-between align-items-center mb-3' do %>
      <div class="text-4xl me-2 me-md-4"><%= category.icon %></div>
      <div class="text-lg font-weight-bold"><%= category.name %></div>
      <div class="text-lg font-weight-bold">$<%= format('%.2f', category.expenses.sum(:amount)) %></div>
      <% end %>
  <% end %>

app/views/shared/_head.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <% if back %>
      <%= link_to("javascript:history.back()", class: "navbar-text text-white text-2xl") do %>
        <i class="fas fa-angle-left text-2xl text-white"></i>
      <% end %>
    <% else %>
      <i class="fa-solid fa-bars text-2xl text-white"></i>
    <% end %>

    <h2 class="navbar-text text-2xl font-semibold text-white text-uppercase"><%= title %></h2>

    <% if title == "categories" || title == "Expenses" %>
        <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "navbar-text text-white text-2xl" do%>
            <i class="fa-solid fa-arrow-right-from-bracket" style="color: #fcfcfc;"></i>
      <% end %>
    <% elsif title == "register" %>
      <%= link_to new_user_session_path, class: "navbar-text text-white text-2xl" do %>
        <span class="font-normal">Next</span>
      <% end %>
    <% elsif title == "login" %>
      <%= link_to new_user_registration_path, class: "navbar-text text-white text-2xl" do %>
        <span class="fas fa-user-plus"></span>
      <% end %>
    <% elsif title == "ForgotPWD?" %>
        <%= link_to new_user_session_path, class: "navbar-text text-white text-2xl" do %>
        <span class="font-normal">Next</span>
    <%end%>
    <% else%>
      <%= link_to sign_out_user_path, class: "navbar-text text-white text-2xl" do %>
        <i class="fa-solid fa-arrow-right-from-bracket" style="color: #fcfcfc;"></i>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/shared/_message.html.erb
<div class="message-container">
    <div class="<%= status %> flex justify-content-between" id="alert-box">
        <% if status == 'notice' %>
            <span class=""><%= notice %></span>
        <% else %>
            <span class=""><%= alert %></span>
        <% end %>
        <div class="d-flex justify-content-end">
        <button type="button" class="btn-close"  onclick='closeMessage()' aria-label="Close"></button>
    </div>
    </div>
</div>

<script>
    function closeMessage() {
        document.getElementById('alert-box').style.display = "none"
    }
</script>